project:
  type: website

website:
  title: "Crime Trend and Spatial Analysis in Chicago (2010 - 2023)"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    includes:
        after_body: include/after_body.html
